export enum View {
  // Phase 1
  LOGIN = 'LOGIN',
  ONBOARDING_GOALS = 'ONBOARDING_GOALS',
  ONBOARDING_EXP = 'ONBOARDING_EXP',
  ONBOARDING_COMMIT = 'ONBOARDING_COMMIT',
  ONBOARDING_FINAL = 'ONBOARDING_FINAL',
  PASSWORD_RESET = 'PASSWORD_RESET',
  
  // Phase 2
  DASHBOARD = 'DASHBOARD',
  TRAINING_LOG = 'TRAINING_LOG',
  NUTRITION_LOG = 'NUTRITION_LOG',
  PROGRESS_CHECKIN = 'PROGRESS_CHECKIN',
  AI_FORM_CHECK = 'AI_FORM_CHECK',
  EXERCISE_LIBRARY = 'EXERCISE_LIBRARY',
  
  // Phase 3
  WEIGHT_PROJECTION = 'WEIGHT_PROJECTION',
  COMPARISON_ENGINE = 'COMPARISON_ENGINE',
  MONTHLY_REVIEW = 'MONTHLY_REVIEW',
  WEIGHT_SUCCESS = 'WEIGHT_SUCCESS',
  STREAK_CALENDAR = 'STREAK_CALENDAR',
  
  // Phase 4
  SKILL_TREE = 'SKILL_TREE',
  XP_SHOP = 'XP_SHOP',
  QUEST_LOG = 'QUEST_LOG',
  QUEST_HISTORY = 'QUEST_HISTORY',
  BADGE_GALLERY = 'BADGE_GALLERY',
  LEVEL_UP = 'LEVEL_UP',
  ULTIMATE_UNLOCK = 'ULTIMATE_UNLOCK',
  PERSONAL_BEST = 'PERSONAL_BEST',
  
  // Phase 5
  AI_COACH_CHAT = 'AI_COACH_CHAT',
  COACH_SELECTION = 'COACH_SELECTION',
  TEAM_HUB = 'TEAM_HUB',
  LEADERBOARD = 'LEADERBOARD',
  PROFILE = 'PROFILE',
  SETTINGS = 'SETTINGS',

  // Phase 6
  RECOVERY_PLAN = 'RECOVERY_PLAN',
  GYM_CHECKIN = 'GYM_CHECKIN'
}

export interface UserState {
  name: string;
  level: number;
  xp: number;
  streak: number;
  weight: number;
  currency: number;
}

export enum CoachPersonality {
  SAGE = 'Sage',
  SERGEANT = 'Sergeant',
  HYPE_MAN = 'Hype-Man'
}